api_version: 3
name: project
description: NVIDIA FLARE sample project yaml file for spleen CT segmentation example
participants:
- name: overseer.example.com
  type: overseer
  org: nvidia
  protocol: https
  api_root: /api/v1
  port: 8443
- name: originalhostname
  type: server
  org: nvidia
  fed_learn_port: 8102
  admin_port: 8103
- name: admin@nvidia.com
  type: admin
  org: nvidia
  role: project_admin
- name: site-1
  type: client
  org: nvidia
- name: site-2
  type: client
  org: nvidia
- name: site-3
  type: client
  org: nvidia
- name: site-4
  type: client
  org: nvidia
- name: site-5
  type: client
  org: nvidia
- name: site-6
  type: client
  org: nvidia
- name: site-7
  type: client
  org: nvidia
- name: site-8
  type: client
  org: nvidia
- name: site-9
  type: client
  org: nvidia
- name: site-10
  type: client
  org: nvidia
- name: site-11
  type: client
  org: nvidia
- name: site-12
  type: client
  org: nvidia
- name: site-13
  type: client
  org: nvidia
- name: site-14
  type: client
  org: nvidia
- name: site-15
  type: client
  org: nvidia
- name: site-16
  type: client
  org: nvidia
- name: site-17
  type: client
  org: nvidia
- name: site-18
  type: client
  org: nvidia
- name: site-19
  type: client
  org: nvidia
- name: site-20
  type: client
  org: nvidia
- name: site-21
  type: client
  org: nvidia
- name: site-22
  type: client
  org: nvidia
- name: site-23
  type: client
  org: nvidia
- name: site-24
  type: client
  org: nvidia
- name: site-25
  type: client
  org: nvidia
- name: site-26
  type: client
  org: nvidia
- name: site-27
  type: client
  org: nvidia
- name: site-28
  type: client
  org: nvidia
- name: site-29
  type: client
  org: nvidia
- name: site-30
  type: client
  org: nvidia
- name: site-31
  type: client
  org: nvidia
- name: site-32
  type: client
  org: nvidia
- name: site-33
  type: client
  org: nvidia
- name: site-34
  type: client
  org: nvidia
- name: site-35
  type: client
  org: nvidia
- name: site-36
  type: client
  org: nvidia
- name: site-37
  type: client
  org: nvidia
- name: site-38
  type: client
  org: nvidia
- name: site-39
  type: client
  org: nvidia
- name: site-40
  type: client
  org: nvidia
- name: site-41
  type: client
  org: nvidia
- name: site-42
  type: client
  org: nvidia
- name: site-43
  type: client
  org: nvidia
- name: site-44
  type: client
  org: nvidia
- name: site-45
  type: client
  org: nvidia
- name: site-46
  type: client
  org: nvidia
- name: site-47
  type: client
  org: nvidia
- name: site-48
  type: client
  org: nvidia
- name: site-49
  type: client
  org: nvidia
- name: site-50
  type: client
  org: nvidia
- name: site-51
  type: client
  org: nvidia
- name: site-52
  type: client
  org: nvidia
- name: site-53
  type: client
  org: nvidia
- name: site-54
  type: client
  org: nvidia
- name: site-55
  type: client
  org: nvidia
- name: site-56
  type: client
  org: nvidia
- name: site-57
  type: client
  org: nvidia
- name: site-58
  type: client
  org: nvidia
- name: site-59
  type: client
  org: nvidia
- name: site-60
  type: client
  org: nvidia
- name: site-61
  type: client
  org: nvidia
- name: site-62
  type: client
  org: nvidia
- name: site-63
  type: client
  org: nvidia
- name: site-64
  type: client
  org: nvidia
- name: site-65
  type: client
  org: nvidia
- name: site-66
  type: client
  org: nvidia
- name: site-67
  type: client
  org: nvidia
- name: site-68
  type: client
  org: nvidia
- name: site-69
  type: client
  org: nvidia
- name: site-70
  type: client
  org: nvidia
- name: site-71
  type: client
  org: nvidia
- name: site-72
  type: client
  org: nvidia
- name: site-73
  type: client
  org: nvidia
- name: site-74
  type: client
  org: nvidia
- name: site-75
  type: client
  org: nvidia
- name: site-76
  type: client
  org: nvidia
- name: site-77
  type: client
  org: nvidia
- name: site-78
  type: client
  org: nvidia
- name: site-79
  type: client
  org: nvidia
- name: site-80
  type: client
  org: nvidia
- name: site-81
  type: client
  org: nvidia
- name: site-82
  type: client
  org: nvidia
- name: site-83
  type: client
  org: nvidia
- name: site-84
  type: client
  org: nvidia
- name: site-85
  type: client
  org: nvidia
- name: site-86
  type: client
  org: nvidia
- name: site-87
  type: client
  org: nvidia
- name: site-88
  type: client
  org: nvidia
- name: site-89
  type: client
  org: nvidia
- name: site-90
  type: client
  org: nvidia
- name: site-91
  type: client
  org: nvidia
- name: site-92
  type: client
  org: nvidia
- name: site-93
  type: client
  org: nvidia
- name: site-94
  type: client
  org: nvidia
- name: site-95
  type: client
  org: nvidia
- name: site-96
  type: client
  org: nvidia
- name: site-97
  type: client
  org: nvidia
- name: site-98
  type: client
  org: nvidia
- name: site-99
  type: client
  org: nvidia
- name: site-100
  type: client
  org: nvidia
builders:
- path: nvflare.lighter.impl.workspace.WorkspaceBuilder
  args:
    template_file: master_template.yml
- path: nvflare.lighter.impl.template.TemplateBuilder
- path: nvflare.lighter.impl.static_file.StaticFileBuilder
  args:
    config_folder: config
    overseer_agent:
      path: nvflare.ha.dummy_overseer_agent.DummyOverseerAgent
      overseer_exists: false
      args:
        sp_end_point: originalhostname:8102:8103
        heartbeat_interval: 6
- path: nvflare.lighter.impl.cert.CertBuilder
- path: nvflare.lighter.impl.signature.SignatureBuilder
